### ISSUE TITLE
Setup carpark & toy cars & camera 

### ISSUE THREAD

**Issue by hansbotnen** [Bruswei/carparkGPT#6]

**Comment by Bruswei** [comment]
Parking lot purchase completed.

**Comment by Bruswei** [comment]
Cars will be stolen by Fredrik from Yijuns children

**Comment by Bruswei** [comment]
"Ikke-rör Robin" camera will be used for this prototype.

**Comment by hansbotnen** [comment]
Toy cars stolen. Closing the issue
